version: '3.8'

services:
  obsidian_bot:
    build:
      context: .
    container_name: obsidian_bot_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${GIT_SSH_KEY_PATH}:/root/.ssh/obsidian_bot_ssh:ro