version: '3.8'

services:
  obsidian_bot:
    build:
      context: .
      args:
        GIT_SSH_KEY_PATH: ${GIT_SSH_KEY_PATH}
    container_name: obsidian_bot_container
    restart: unless-stopped
    env_file:
      - .env